name: Apply using Github Action

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm" # Enable caching for npm dependencies

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run Prettier check
      - name: Run Prettier Check
        run: |
          npx prettier --check "**/*.{js,jsx,ts,tsx,json,css,scss,md}"

      # Step 5: Build the project (if applicable)
      - name: Build project
        run: npm run build --if-present

      # Step 6: Deploy to GitHub Pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy
