name: Apply using Github Action

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Step to install dependencies
      - name: Install dependencies
        run: npm install # Use npm install instead of npm ci for more flexibility

      # Step to run Prettier check
      - name: Run Prettier Check
        run: |
          npx prettier --check "**/*.{js,jsx,ts,tsx,json,css,scss,md}"  # You can adjust file extensions if necessary

      # If Prettier check fails, the job will fail here. Add this step only if you want to enforce style guidelines.

      # Run build if applicable
      - name: Build project
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy 🚀
        if: success() # Ensure deployment only happens if the build and tests are successful
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy
